import ReactDOM from 'react-dom';
import React from 'react';
import Schedule from './components/Schedule';
import AdminSchedule from './components/AdminSchedule';
import PrintSchedule from './components/PrintSchedule';
import Profile from './components/Profile';
import jquery from 'jquery';
import 'babel-polyfill';
window.PrintSchedule = PrintSchedule;
window.AdminSchedule = AdminSchedule;
window.Profile = Profile;
window.Schedule = Schedule;
window.ReactDOM = ReactDOM;
window.React = React;
window.$ = jquery;
